```sql
-- COPYRIGHT (C) 2022 DE STAAT DER NEDERLANDEN, MINISTERIE VAN VOLKSGEZONDHEID, WELZIJN EN SPORT.
-- LICENSED UNDER THE EUROPEAN UNION PUBLIC LICENCE V. 1.2 - SEE HTTPS://GITHUB.COM/MINVWS/NL-CONTACT-TRACING-APP-COORDINATIONFOR MORE INFORMATION.
```

# **INTRODUCTIONS**

---

The code is separated into multiple sections:

1. **[Flow Diagrams](#flow-diagrams)**
2. **[Dependencies](#dependencies)**
3. **[Input Layer](#input-layer)**
4. **[Intermediate Layer](#intermediate-layer)**
5. **[Ouput Layer](#output-layer)**
6. **[Report Layer](#report-layer)**


# **FLOW DIAGRAMS**

---

[![](https://mermaid.ink/img/pako:eNqNk11rwjAUhv9KyFUdKvixDXoxmGwXgtihsBsrJTZHzdamIUkdTvzvO2rrR7WdvUlJ3vO85-ScbGiYcKAunUfJT7hk2hIyGPmS4GfS2UIztSR9qVJLBmwN-nAy1s7rb6qhFyWzGmk0iE9XLAyFhIBDJFagBZiA8VhIYSxo4MFDMzQrn6L4hYwnjrFsIeSiNj0AQfIrT4yLgQtm4cJ6T-hPHHEmKMd4qS3k3t8DvPbEyVIm53kSFTEpgefETN26rS6oOidVdg3rgqJ7rSAKNOarVCRAnxVCCpX4dAQq0Xkt9HDstffgj17LmeQtuLj3rJ5preyGfDocNL9MIo_IFmk0cXvO3DlrGCUwHv1IE30-h4MSo9zgn-h2SZpgrIixk0dMuxLTua9ar1NJ6Z4oeTfujHy8jrwuoVuJeL6BwFEI8lG4E_NUkUmACwRGMXnWflqnMT4cJji--s1u26d2CTH41MVfzvT3bhK2qEsVR8o7FzbRFN0jA3XKUpuM1zKkrtUp5KI3wXCc4ky1_QNKJmpn)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNqNk11rwjAUhv9KyFUdKvixDXoxmGwXgtihsBsrJTZHzdamIUkdTvzvO2rrR7WdvUlJ3vO85-ScbGiYcKAunUfJT7hk2hIyGPmS4GfS2UIztSR9qVJLBmwN-nAy1s7rb6qhFyWzGmk0iE9XLAyFhIBDJFagBZiA8VhIYSxo4MFDMzQrn6L4hYwnjrFsIeSiNj0AQfIrT4yLgQtm4cJ6T-hPHHEmKMd4qS3k3t8DvPbEyVIm53kSFTEpgefETN26rS6oOidVdg3rgqJ7rSAKNOarVCRAnxVCCpX4dAQq0Xkt9HDstffgj17LmeQtuLj3rJ5preyGfDocNL9MIo_IFmk0cXvO3DlrGCUwHv1IE30-h4MSo9zgn-h2SZpgrIixk0dMuxLTua9ar1NJ6Z4oeTfujHy8jrwuoVuJeL6BwFEI8lG4E_NUkUmACwRGMXnWflqnMT4cJji--s1u26d2CTH41MVfzvT3bhK2qEsVR8o7FzbRFN0jA3XKUpuM1zKkrtUp5KI3wXCc4ky1_QNKJmpn)

Required steps:

1. `ADD REQUIRMENT STEP LIST HERE!`

- **<font color=teal>IL</font>**: Intermediate Layer
- **<font color=teal>OL</font>**: Output Layer

# **DEPENDENCIES**

---

```json
{
    "depends-on": [
        "src/DataFactory/Utils/Functions.ipynb",
        "src/DataFactory/Utils/Schemas.ipynb",
        "src/DataFactory/Utils/Protos.ipynb"
        // Additional dependencies (!NOTE! DO NOT FORGET THE COMMA (i.e. ,))
    ]
}
```

# **INPUT LAYER**

---

## **<span style='color:teal'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSSTAGE].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]'))
CREATE TABLE [VWSSTAGE].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DATE_OF_REPORT] [VARCHAR] (100) NULL,
    [DATE_FIRST_DAY] [VARCHAR] (100) NULL,
    [VALUE_TYPE] [VARCHAR] (100) NULL,
    [VALUE_NAME] [VARCHAR] (100) NULL,
    [REPORT_STATUS] [VARCHAR] (100) NULL,
    [VALUE] [VARCHAR] (100) NULL
);
GO

# **INTERMEDIATE LAYER**

---

## **<span style='color:teal'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]'))
CREATE TABLE [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DATE_OF_REPORT] [DATETIME] NULL,
    [DATE_FIRST_DAY] [DATETIME] NULL,
    [VALUE_TYPE] [VARCHAR] (100) NULL,
    [VALUE_NAME] [VARCHAR] (100)  NULL,
    [REPORT_STATUS] [VARCHAR] (100) NULL,
    [VALUE] [BIGINT] NULL
);
GO

## **<span style='color:teal'>STORED PROCEDURES</span>**

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): STAGING TO INTERMEDIATE.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_IL_RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
AS
BEGIN
    INSERT INTO [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL] (
        [DATE_OF_REPORT],
        [DATE_FIRST_DAY],
        [VALUE_TYPE],
        [VALUE_NAME],
        [REPORT_STATUS],
        [VALUE] 
    )
    SELECT
        [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_OF_REPORT]) AS [DATE_OF_REPORT],
        [DBO].[TRY_CONVERT_TO_DATETIME]([DATE_FIRST_DAY]) AS [DATE_FIRST_DAY],
        [VALUE_TYPE],
        UPPER([VALUE_NAME]),
        [REPORT_STATUS],
        CAST([VALUE] AS BIGINT) AS [VALUE]
    FROM
        [VWSSTAGE].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSSTAGE].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL])
END;
GO

# **OUTPUT LAYER**

---

## **<span style='color:teal'>VACCINE ADMINISTERED NL</span>**

### **<span style='color:cadetblue'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL]'))
CREATE TABLE [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DATE_FIRST_DAY] [DATETIME] NULL,
	[DATE_START_UNIX] [BIGINT] NULL,
	[DATE_END_UNIX] [BIGINT] NULL,
	[VALUE_TYPE] [VARCHAR] (100) NULL,
	[REPORT_STATUS] [VARCHAR] (100) NULL,
	[ASTRAZENECA] [BIGINT] NULL,
	[BIONTECH/PFIZER] [BIGINT] NULL,
	[CUREVAC] [BIGINT] NULL,
	[JANSSEN] [BIGINT] NULL,
	[MODERNA] [BIGINT] NULL,
	[SANOFI] [BIGINT] NULL,
	[NOVAVAX] [BIGINT] NULL
);
GO

-- 2) CREATE INDEX(S).....
DROP INDEX IF EXISTS [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_NL] 
	ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL]
GO

CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_NL]
    ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] (
		[DATE_LAST_INSERTED]
	)
	INCLUDE(
		[DATE_FIRST_DAY], 
		[DATE_START_UNIX], 
		[DATE_END_UNIX], 
		[VALUE_TYPE], 
		[REPORT_STATUS]
	);
GO

### **<span style='color:cadetblue'>STORED PROCEDURES</span>**

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_ADMINISTERED_NL]
AS
BEGIN
    WITH CTE AS (
        SELECT
            [DATE_FIRST_DAY],
            [VALUE_TYPE],
            [VALUE_NAME],
            [REPORT_STATUS],
            [VALUE]
        FROM
            [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
        WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL])
            AND LOWER([VALUE_TYPE]) IN ('vaccine_administered')
    ),
    PIVOT_CTE AS (
        SELECT 
            [ASTRAZENECA], 
            [BIONTECH/PFIZER], 
            [CUREVAC], 
            [JANSSEN], 
            [MODERNA], 
            [SANOFI], 
            [NOVAVAX] ,
            [DATE_FIRST_DAY],
            [VALUE_TYPE],
            [REPORT_STATUS]
        FROM CTE
        PIVOT  (  
            SUM ([VALUE])  
            FOR [VALUE_NAME] IN (
                [ASTRAZENECA],
                [BIONTECH/PFIZER],
                [CUREVAC],
                [JANSSEN],
                [MODERNA],
                [SANOFI],
                [NOVAVAX] 
            )
        ) AS PivotTable  
    )
    INSERT INTO [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] (
        [ASTRAZENECA],
        [BIONTECH/PFIZER],
        [CUREVAC], 
        [JANSSEN],         
        [MODERNA],         
        [SANOFI],         
        [NOVAVAX],
        [DATE_FIRST_DAY],
        [DATE_START_UNIX],    
        [DATE_END_UNIX],   
        [VALUE_TYPE],  
        [REPORT_STATUS]
    )
    SELECT  
        ISNULL([ASTRAZENECA], 0),
        ISNULL([BIONTECH/PFIZER], 0),
        ISNULL([CUREVAC], 0),
        ISNULL([JANSSEN], 0),
        ISNULL([MODERNA], 0),
        ISNULL([SANOFI], 0),
        ISNULL([NOVAVAX], 0),
        [DATE_FIRST_DAY],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_FIRST_DAY]),
        [dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY,6,[DATE_FIRST_DAY])),
        [VALUE_TYPE],
        [REPORT_STATUS]
    FROM PIVOT_CTE
    ORDER BY [DATE_FIRST_DAY]
END;
GO

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_ADMINISTERED_NL] AS
WITH CTE AS (
    SELECT
        [DATE_START_UNIX],
        [DATE_END_UNIX],
        [ASTRAZENECA] AS [ASTRA_ZENECA],
        [BIONTECH/PFIZER] AS [PFIZER],
        -- [CUREVAC] AS [CURE_VAC],
        [JANSSEN],
        [MODERNA],
        [NOVAVAX],
        -- [SANOFI],
        [ASTRAZENECA] + [BIONTECH/PFIZER] + [MODERNA]  + [JANSSEN] + [NOVAVAX] AS [TOTAL],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
    FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] WITH(NOLOCK))
)
SELECT
    [DATE_START_UNIX],
    [DATE_END_UNIX],
    [ASTRA_ZENECA],
    [PFIZER],
    [JANSSEN],
    [MODERNA],
    [NOVAVAX],
    [TOTAL],
    [DATE_OF_INSERTION_UNIX]
FROM CTE
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_ADMINISTERED_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_administered',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL]'))
CREATE TABLE [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DOSES] [BIGINT] NOT NULL,
	[DATE_START_UNIX] [BIGINT] NOT NULL,
	[DATE_END_UNIX] [BIGINT] NOT NULL
);
GO

-- 2) CREATE INDEX(S).....
DROP INDEX IF EXISTS [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_PLANNED_NL] 
	ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
GO

CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
    ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
		[DATE_LAST_INSERTED]
	)
GO

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
AS
BEGIN
    WITH CTE
    AS (
        SELECT
            CAST([DATE_FIRST_DAY] AS DATE) AS [DATE_FIRST_DAY],
            CAST([DATE_LAST_INSERTED] AS DATE) AS [DATE_LAST_INSERTED],
            [REPORT_STATUS],
            SUM([VALUE]) AS [VALUE]
        FROM
            [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
        WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL])
            AND LOWER([VALUE_TYPE]) = 'vaccine_administered'
        GROUP BY
            CAST([DATE_FIRST_DAY] AS DATE),
            CAST([DATE_LAST_INSERTED] AS DATE),
            [REPORT_STATUS]
    ),
    AGGR_CTE
    AS (        
        SELECT
            [VALUE] - LAG([VALUE],1,0) OVER (ORDER BY [DATE_FIRST_DAY] ASC) AS [DOSES],
            [DATE_FIRST_DAY] AS [DATE_START],
            DATEADD(day, -1, LEAD([DATE_FIRST_DAY], 1, NULL) OVER (ORDER BY [DATE_FIRST_DAY] ASC)) AS [DATE_END]
        FROM CTE
    )
    INSERT INTO [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
        [DOSES],
        [DATE_START_UNIX],
        [DATE_END_UNIX]
    )
    SELECT
        [DOSES],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_START]),
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_END])
    FROM
		AGGR_CTE
	WHERE [DATE_START] <= CAST(GETDATE() AS DATE) 
        AND CAST(GETDATE() AS DATE) <= [DATE_END]
END;
GO

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_ADMINISTERED_PLANNED_NL] AS
	SELECT
		[DOSES],
		[DATE_START_UNIX],
		[DATE_END_UNIX],
		[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
	FROM 
		[VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK)
	WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK))
GO

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_ADMINISTERED_PLANNED_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_administered_planned',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_END_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE ADMINISTERED ESTIMATE NL</span>**

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_ADMINISTERED_ESTIMATE_NL] AS
    SELECT
        [DATE_START_UNIX],
        [DATE_END_UNIX],
        [ASTRAZENECA] AS [ASTRA_ZENECA],
        [BIONTECH/PFIZER] AS [PFIZER],
        -- [CUREVAC] AS [CURE_VAC],
        [JANSSEN],
        [MODERNA],
        -- [NOVAVAX],
        -- [SANOFI],
        [ASTRAZENECA] + [BIONTECH/PFIZER] + [MODERNA] +  [JANSSEN]  AS [TOTAL],
        [DBO].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
    FROM 
        [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_NL] WITH(NOLOCK))
        AND LOWER([REPORT_STATUS]) = 'estimated'
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_ADMINISTERED_ESTIMATE_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_administered_estimate',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 0
    WHEN 'acceptance' THEN 0
    ELSE 0
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE DELIVERY NL</span>**

### **<span style='color:cadetblue'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSDEST].[RIVM_VACCINE_DELIVERY_NL]'))
CREATE TABLE [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DATE_FIRST_DAY]      DATETIME      NULL,
    [DATE_START_UNIX]     BIGINT        NULL,
    [DATE_END_UNIX]       BIGINT        NULL,
    [VALUE_TYPE]          VARCHAR (100) NULL,
    [REPORT_STATUS]       VARCHAR (100) NULL,
    [VALUE]               BIGINT        NULL,
    [DATE_OF_REPORT_UNIX] BIGINT        NULL
);
GO

-- 2) CREATE INDEX(S).....
DROP INDEX IF EXISTS [NCIX_DLI_RIVM_VACCINE_DELIVERY_NL] 
	ON [VWSDEST].[RIVM_VACCINE_DELIVERY_NL]
GO

CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINE_DELIVERY_NL]
    ON [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] (
		[DATE_LAST_INSERTED]
	)
	INCLUDE(
		[DATE_FIRST_DAY], 
		[DATE_START_UNIX], 
		[DATE_END_UNIX], 
		[VALUE_TYPE], 
		[REPORT_STATUS], 
		[VALUE]
	);
GO

### **<span style='color:cadetblue'>STORED PROCEDURES</span>**

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_DELIVERY_NL]
AS
BEGIN
    INSERT INTO [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] (
        [DATE_OF_REPORT_UNIX],
        [DATE_FIRST_DAY],
        [DATE_START_UNIX],
        [DATE_END_UNIX],
        [VALUE_TYPE],
        [REPORT_STATUS],
        [VALUE]
    )
    SELECT
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_REPORT]),
        [DATE_FIRST_DAY],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_FIRST_DAY]),
        [dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY,6,[DATE_FIRST_DAY])),
        [VALUE_TYPE],
        [REPORT_STATUS],
        [VALUE]
    FROM
        [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL])
        AND LOWER([VALUE_TYPE]) = 'vaccine_delivery'
    ORDER BY
        [DATE_FIRST_DAY]
END;
GO

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_DELIVERY_NL] AS
    SELECT
        [VALUE] AS [TOTAL],
        [DATE_START_UNIX],
        [DATE_OF_REPORT_UNIX],
        [DATE_END_UNIX],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
    FROM 
        [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] WITH(NOLOCK))
        AND LOWER([REPORT_STATUS]) = 'reported'
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_DELIVERY_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_delivery',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE DELIVERY ESTIMATE NL</span>**

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_DELIVERY_ESTIMATE_NL] AS
    SELECT
        [VALUE] AS [TOTAL],
        [DATE_START_UNIX],
        [DATE_END_UNIX],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
    FROM 
        [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_DELIVERY_NL] WITH(NOLOCK))
        AND LOWER([REPORT_STATUS]) = 'estimated'
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_DELIVERY_ESTIMATE_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_delivery_estimate',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE DELIVERY PER SUPPLIER NL</span>**

### **<span style='color:cadetblue'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL]'))
BEGIN
	CREATE TABLE [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] (
		[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
		[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
		[DATE_FIRST_DAY] [DATETIME]      NULL,
		[DATE_OF_REPORT] [DATETIME]      NULL,
		[DATE_START_UNIX] [BIGINT]        NULL,
		[DATE_END_UNIX] [BIGINT]        NULL,
		[VALUE_TYPE] [VARCHAR] (100) NULL,
		[REPORT_STATUS] [VARCHAR] (100) NULL,
		[ASTRAZENECA] [BIGINT]        NULL,
		[BIONTECH/PFIZER] [BIGINT]        NULL,
		[CUREVAC] [BIGINT]        NULL,
		[JANSSEN] [BIGINT]        NULL,
		[MODERNA] [BIGINT]        NULL,
		[SANOFI] [BIGINT]        NULL,
		-- [NOVAVAX] [BIGINT]        NULL,
		[TOTAL_VALUE] [BIGINT]        NULL
	);
END
--ELSE
--BEGIN
--    IF NOT EXISTS (SELECT * FROM SYS.COLUMNS 
--    WHERE [NAME] IN (N'NOVAVAX')
--    AND [OBJECT_ID] = OBJECT_ID(N'[VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL]'))
--        BEGIN
--            ALTER TABLE [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] 
--            ADD 
--                [NOVAVAX] [BIGINT]        NULL;
--	    END
--END
GO

-- 2) CREATE INDEX(S).....
DROP INDEX IF EXISTS [NCIX_DLI_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] 
	ON [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL]
GO

CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL]
    ON [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] (
		[DATE_LAST_INSERTED]
	)
    INCLUDE(
		[DATE_FIRST_DAY], 
		[DATE_OF_REPORT], 
		[DATE_START_UNIX], 
		[DATE_END_UNIX]
	);
GO

### **<span style='color:cadetblue'>STORED PROCEDURES</span>**

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL]
AS
BEGIN
    WITH CTE AS (
        SELECT 
            [DATE_FIRST_DAY],
            [DATE_OF_REPORT],
            [VALUE_TYPE],
            [VALUE_NAME],
            [REPORT_STATUS],
            [VALUE]
        FROM 
            [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
        WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]) 
            AND LOWER([VALUE_TYPE]) = 'vaccine_delivery_weekly' 
    ),
    GROUPED_CTE AS (
        SELECT
            [DATE_FIRST_DAY],
            [VALUE_TYPE],
            SUM([VALUE]) AS [TOTAL_VALUE]
        FROM 
            CTE
        GROUP BY [VALUE_TYPE], [DATE_FIRST_DAY]
    ),
    PIVOT_CTE AS (
        SELECT 
            [ASTRAZENECA], 
            [BIONTECH/PFIZER], 
            [CUREVAC], 
            [JANSSEN], 
            [MODERNA], 
            [SANOFI],
            -- [NOVAVAX],
            [DATE_FIRST_DAY],
            [DATE_OF_REPORT],
            [VALUE_TYPE],
            [REPORT_STATUS]
        FROM CTE
        PIVOT (  
            SUM ([VALUE])  
            FOR [VALUE_NAME] IN  ( 
                [ASTRAZENECA],
                [BIONTECH/PFIZER],
                [CUREVAC],
                [JANSSEN],
                [MODERNA],
                [SANOFI]
                -- [NOVAVAX]
            )  
        ) AS PivotTable  
    )
    INSERT INTO [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] (
        [AstraZeneca],   
        [BioNTech/Pfizer],
        [CureVac], 
        [Janssen],         
        [Moderna],         
        [Sanofi],   
        -- [Novavax],
        [TOTAL_VALUE],
        [DATE_FIRST_DAY],
        [DATE_OF_REPORT],
        [DATE_START_UNIX], 
        [DATE_END_UNIX],   
        [VALUE_TYPE],  
        [REPORT_STATUS]   
    )
    SELECT
        ISNULL([AstraZeneca] ,0), 
        ISNULL([BioNTech/Pfizer] ,0),
        ISNULL([CureVac], 0),     
        ISNULL([Janssen], 0),      
        ISNULL([Moderna], 0),        
        ISNULL([Sanofi], 0), 
        --  ISNULL([Novavax], 0),
        T2.[TOTAL_VALUE],
        T1.[DATE_FIRST_DAY],
        T1.[DATE_OF_REPORT],
        [dbo].[CONVERT_DATETIME_TO_UNIX](T1.[DATE_FIRST_DAY]),
        [dbo].[CONVERT_DATETIME_TO_UNIX](DATEADD(DAY,6,T1.[DATE_FIRST_DAY])),
        T1.[VALUE_TYPE],
        T1.[REPORT_STATUS]
    FROM 
        PIVOT_CTE T1
    LEFT JOIN GROUPED_CTE T2 
        ON T1.[DATE_FIRST_DAY] = T2.[DATE_FIRST_DAY] AND T1.[VALUE_TYPE] = T2.[VALUE_TYPE]
    ORDER BY [DATE_FIRST_DAY]
END;
GO

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] AS
    SELECT
        [ASTRAZENECA] AS [ASTRA_ZENECA],
        [BIONTECH/PFIZER] AS [BIO_N_TECH_PFIZER],
        -- [CUREVAC] AS [CURE_VAC],
        [JANSSEN],
        [MODERNA],
        -- [NOVAVAX],
        -- [SANOFI],
        [TOTAL_VALUE] AS [TOTAL],
        IIF(LOWER([REPORT_STATUS]) = 'estimated', 'true', 'false') AS [IS_ESTIMATE],
        [DATE_START_UNIX],
        [DATE_END_UNIX],
        [dbo].[CONVERT_DATETIME_TO_ISO_WEEKNUMBER]([DATE_FIRST_DAY]) AS [WEEK_NUMBER],
        -- ROW_NUMBER() OVER (ORDER BY [DATE_START_UNIX]) AS [WEEK_NUMBER],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_REPORT]) AS [DATE_OF_REPORT_UNIX],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
    FROM 
        [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] WITH(NOLOCK))
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_delivery_per_supplier',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE DELIVERY PER SUPPLIER ESTIMATE NL</span>**

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_ESTIMATE_NL] AS
    SELECT
        SUM([TOTAL_VALUE]) AS [DOSES],
        COUNT(*) AS [TIME_SPAN_WEEKS],
        MIN([DATE_START_UNIX]) AS [DATE_START_UNIX],
        MAX([DATE_END_UNIX]) AS [DATE_END_UNIX],
        MAX([dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_OF_REPORT])) AS [DATE_OF_REPORT_UNIX],
        MAX([dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED])) AS [DATE_OF_INSERTION_UNIX]
    FROM 
        [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] WITH(NOLOCK)
    WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_DELIVERY_PER_SUPPLIER_NL] WITH(NOLOCK))
        AND [REPORT_STATUS] = 'estimated'
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_DELIVERY_PER_SUPPLIER_ESTIMATE_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_delivery_estimate_time_span',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_START_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

## **<span style='color:teal'>VACCINE ADMINISTERED PLANNED NL</span>**

### **<span style='color:cadetblue'>TABLES</span>**

In [ ]:
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 1) CREATE TABLE(S).....
IF NOT EXISTS (SELECT * FROM [SYS].[TABLES] WHERE [OBJECT_ID] = OBJECT_ID('[VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL]'))
CREATE TABLE [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
	[ID] [BIGINT] PRIMARY KEY IDENTITY(1,1),
	[DATE_LAST_INSERTED] [DATETIME] DEFAULT GETDATE(),
	[DOSES] [BIGINT] NOT NULL,
	[DATE_START_UNIX] [BIGINT] NOT NULL,
	[DATE_END_UNIX] [BIGINT] NOT NULL
);
GO

-- 2) CREATE INDEX(S).....
DROP INDEX IF EXISTS [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_PLANNED_NL] 
	ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
GO

CREATE NONCLUSTERED INDEX [NCIX_DLI_RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
    ON [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
		[DATE_LAST_INSERTED]
	)
GO

### **<span style='color:cadetblue'>STORED PROCEDURES</span>**

In [ ]:
-- 1) CREATE STORED PROCEDURE(S): INTERMEDIATE TO DESTINATION.....
CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_OL_RIVM_VACCINE_ADMINISTERED_PLANNED_NL]
AS
BEGIN
    WITH CTE
    AS (
        SELECT
            CAST([DATE_FIRST_DAY] AS DATE) AS [DATE_FIRST_DAY],
            CAST([DATE_LAST_INSERTED] AS DATE) AS [DATE_LAST_INSERTED],
            [REPORT_STATUS],
            SUM([VALUE]) AS [VALUE]
        FROM
            [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL]
        WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSINTER].[RIVM_VACCINE_DELIVERIES_ADMINISTERED_NL])
            AND LOWER([VALUE_TYPE]) = 'vaccine_administered'
        GROUP BY
            CAST([DATE_FIRST_DAY] AS DATE),
            CAST([DATE_LAST_INSERTED] AS DATE),
            [REPORT_STATUS]
    ),
    AGGR_CTE
    AS (        
        SELECT
            [VALUE] - LAG([VALUE],1,0) OVER (ORDER BY [DATE_FIRST_DAY] ASC) AS [DOSES],
            [DATE_FIRST_DAY] AS [DATE_START],
            DATEADD(day, -1, LEAD([DATE_FIRST_DAY], 1, NULL) OVER (ORDER BY [DATE_FIRST_DAY] ASC)) AS [DATE_END]
        FROM CTE
    )
    INSERT INTO [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] (
        [DOSES],
        [DATE_START_UNIX],
        [DATE_END_UNIX]
    )
    SELECT
        [DOSES],
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_START]),
        [dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_END])
    FROM
		AGGR_CTE
	WHERE [DATE_START] <= CAST(GETDATE() AS DATE) 
        AND CAST(GETDATE() AS DATE) <= [DATE_END]
END;
GO

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSDEST].[V_RIVM_VACCINE_ADMINISTERED_PLANNED_NL] AS
	SELECT
		[DOSES],
		[DATE_START_UNIX],
		[DATE_END_UNIX],
		[dbo].[CONVERT_DATETIME_TO_UNIX]([DATE_LAST_INSERTED]) AS [DATE_OF_INSERTION_UNIX]
	FROM 
		[VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK)
	WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK))
GO

### **<span style='color:cadetblue'>VIEWS | CONFIGURATION</span>**

In [ ]:
-- 1) SET ENVIRONMENTAL VARIABLES.....
DECLARE @view_name VARCHAR(256) = 'VWSDEST.V_RIVM_VACCINE_ADMINISTERED_PLANNED_NL',
        @view_description VARCHAR(256),
        @item_name VARCHAR(256) = 'vaccine_administered_planned',
        @config_description VARCHAR(256),
        @constraint_value VARCHAR(50) = NULL,
        @constraint_key_name VARCHAR(50) = NULL,
        @grouped_key_name VARCHAR(50) = NULL,
        @grouped_last_update_name VARCHAR(50) = NULL,
        @proto_name VARCHAR(50) = 'NL',
        @columns VARCHAR(256) = '*',
        @layout_type_id INT = 1,
        @last_update_name VARCHAR(50) = 'DATE_END_UNIX',
        @is_active INT;
        
SET @is_active = CASE LOWER('#{ Environment }#')
    WHEN 'production' THEN 1
    WHEN 'acceptance' THEN 1
    ELSE 1
END;

SET @view_description = CONCAT('VIEW: ', @view_name, ' FOR ', @item_name);
SET @config_description = CONCAT('VIEW CONFIGURATION: ', @view_name, ' FOR ', @item_name);

-- 2) DETERMINE VIEW ID & CONFIGURATION ID
DECLARE @constrained INT,
        @grouped INT,
        @view_id BIGINT,
        @config_id BIGINT;

SET @constrained = CASE 
    WHEN @constraint_key_name IS NULL THEN 0
    ELSE 1
END;
SET @grouped = CASE 
    WHEN @grouped_key_name IS NULL THEN 0
    ELSE 1
END;

DELETE FROM [DATATINO_PROTO_1].[CONFIGURATIONS]
WHERE [ID] IN (
    SELECT
        configs.[ID]
    FROM [DATATINO_PROTO_1].[VIEWS] views
    INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
        AND configs.[NAME] = @item_name
    INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
        AND protos.[NAME] = @proto_name
);

SELECT 
    @view_id = [ID]
FROM [DATATINO_PROTO_1].[VIEWS]
WHERE ISNULL([CONSTRAINT_VALUE], 'X') = ISNULL(@constraint_value, 'X')
    AND ISNULL([CONSTRAINT_KEY_NAME], 'X') = ISNULL(@constraint_key_name, 'X')
    AND ISNULL([GROUPED_KEY_NAME], 'X') = ISNULL(@grouped_key_name, 'X')
    AND ISNULL([GROUPED_LAST_UPDATE_NAME], 'X') = ISNULL(@grouped_last_update_name, 'X')
    AND [NAME] = @view_name;

SELECT
    @config_id = configs.[ID]
FROM [DATATINO_PROTO_1].[VIEWS] views
INNER JOIN [DATATINO_PROTO_1].[CONFIGURATIONS] AS configs ON views.[ID] = configs.[VIEW_ID]
    AND configs.[NAME] = @item_name
    AND configs.[VIEW_ID] = @view_id
INNER JOIN [DATATINO_PROTO_1].[PROTOS] AS protos ON protos.[ID] = configs.[PROTO_ID]
    AND protos.[NAME] = @proto_name
WHERE views.[NAME] = @view_name;

-- 3) UPSERT PROTO VIEW(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_VIEW]
    @id = @view_id,
    @view_name = @view_name,
    @description = @view_description,
    @last_update_name = @last_update_name,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;

-- 4) UPSERT PROTO CONFIGURATION(S).....
EXECUTE [DATATINO_PROTO_1].[UPSERT_CONFIGURATION]
    @id = @config_id,
    @proto_name = @proto_name,
    @description =  @config_description,
    @view_name = @view_name,
    @item_name = @item_name,
    @constrained = @constrained,
    @grouped = @grouped,
    @columns = @columns,
    @mapping = '=LOWER()',
    @layout_type_id = @layout_type_id,
    @active = @is_active,
    @constraint_key_name = @constraint_key_name,
    @constraint_value = @constraint_value,
    @grouped_key_name = @grouped_key_name,
    @grouped_last_update_name = @grouped_last_update_name;
GO

# **REPORT LAYER**

---

### **<span style='color:cadetblue'>VIEWS</span>**

In [ ]:
-- 1) CREATE VIEW(S).....
CREATE OR ALTER VIEW [VWSREPORT].[V_RIVM_VACCINE_ADMINISTERED_PLANNED_NL] AS
	SELECT
		[DOSES],
		[DATE_START_UNIX],
		[DATE_END_UNIX],
		[DATE_LAST_INSERTED] AS [DATE_OF_INSERTION]
	FROM 
		[VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK)
	WHERE [DATE_LAST_INSERTED] = (SELECT MAX([DATE_LAST_INSERTED]) FROM [VWSDEST].[RIVM_VACCINE_ADMINISTERED_PLANNED_NL] WITH(NOLOCK))
GO